"""
PRISMA 2020 流程图自动生成器

生成符合PRISMA 2020声明的流程图
输出SVG + HTML两种格式
"""


def generate_prisma_flowchart(data: dict) -> str:
    """
    生成PRISMA 2020流程图 (SVG)
    
    Args:
        data: {
            "identification": {
                "records_from_databases": 2847,
                "records_from_registers": 423,
            },
            "screening": {
                "records_after_dedup": 2947,
                "records_screened": 2947,
                "records_excluded": 2461,
            },
            "eligibility": {
                "full_texts_assessed": 486,
                "full_texts_excluded": 434,
                "exclusion_reasons": {
                    "非RCT设计": 156,
                    "干预不符": 98,
                    "结局指标不符": 82,
                    "重复发表": 56,
                    "无法获取全文": 42,
                }
            },
            "included": {
                "studies_included": 52,
                "studies_in_qualitative": 52,
                "studies_in_quantitative": 48,
            }
        }
    """
    
    id_data = data.get("identification", {})
    screen_data = data.get("screening", {})
    elig_data = data.get("eligibility", {})
    incl_data = data.get("included", {})
    
    # 默认值
    db_records = id_data.get("records_from_databases", 0)
    register_records = id_data.get("records_from_registers", 0)
    total_identified = db_records + register_records
    after_dedup = screen_data.get("records_after_dedup", total_identified)
    removed_dup = total_identified - after_dedup
    records_screened = screen_data.get("records_screened", after_dedup)
    records_excluded_screen = screen_data.get("records_excluded", 0)
    full_texts = elig_data.get("full_texts_assessed", 0)
    full_texts_excluded = elig_data.get("full_texts_excluded", 0)
    exclusion_reasons = elig_data.get("exclusion_reasons", {})
    included = incl_data.get("studies_included", 0)
    qual_included = incl_data.get("studies_in_qualitative", included)
    quant_included = incl_data.get("studies_in_quantitative", included)
    
    # 构建排除原因文字
    exclusion_text = ""
    y_start = 320
    for reason, count in exclusion_reasons.items():
        exclusion_text += f'    <text x="680" y="{y_start}" font-size="11" fill="#94a3b8" font-family="Inter, sans-serif">{reason}: {count}</text>\n'
        y_start += 18
    
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 900 620" style="background:#0f1629;font-family:Inter,sans-serif">
  <defs>
    <linearGradient id="boxGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:rgba(59,130,246,0.15)"/>
      <stop offset="100%" style="stop-color:rgba(139,92,246,0.15)"/>
    </linearGradient>
    <linearGradient id="exclGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:rgba(239,68,68,0.1)"/>
      <stop offset="100%" style="stop-color:rgba(239,68,68,0.05)"/>
    </linearGradient>
    <linearGradient id="inclGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:rgba(16,185,129,0.15)"/>
      <stop offset="100%" style="stop-color:rgba(16,185,129,0.05)"/>
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="2" result="blur"/>
      <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
    </filter>
  </defs>
  
  <!-- Title -->
  <text x="450" y="30" text-anchor="middle" font-size="18" font-weight="700" fill="#e2e8f0">PRISMA 2020 流程图</text>
  <text x="450" y="50" text-anchor="middle" font-size="12" fill="#64748b">Generated by MetaForge</text>
  
  <!-- Phase Labels -->
  <rect x="20" y="70" width="250" height="30" rx="6" fill="rgba(59,130,246,0.2)" stroke="#3b82f6" stroke-width="1"/>
  <text x="145" y="90" text-anchor="middle" font-size="13" font-weight="600" fill="#60a5fa">Identification</text>
  
  <rect x="300" y="70" width="250" height="30" rx="6" fill="rgba(139,92,246,0.2)" stroke="#8b5cf6" stroke-width="1"/>
  <text x="425" y="90" text-anchor="middle" font-size="13" font-weight="600" fill="#a78bfa">Screening</text>
  
  <rect x="580" y="70" width="300" height="30" rx="6" fill="rgba(236,72,153,0.2)" stroke="#ec4899" stroke-width="1"/>
  <text x="730" y="90" text-anchor="middle" font-size="13" font-weight="600" fill="#f472b6">Eligibility</text>
  
  <!-- IDENTIFICATION -->
  <!-- Database records -->
  <rect x="40" y="120" width="210" height="70" rx="10" fill="url(#boxGrad)" stroke="#3b82f6" stroke-width="1.5" filter="url(#glow)"/>
  <text x="145" y="145" text-anchor="middle" font-size="12" fill="#94a3b8">来自数据库的记录</text>
  <text x="145" y="170" text-anchor="middle" font-size="20" font-weight="700" fill="#e2e8f0">{db_records:,}</text>
  
  <!-- Register records -->
  <rect x="40" y="210" width="210" height="60" rx="10" fill="url(#boxGrad)" stroke="#3b82f6" stroke-width="1.5"/>
  <text x="145" y="235" text-anchor="middle" font-size="12" fill="#94a3b8">来自注册库的记录</text>
  <text x="145" y="255" text-anchor="middle" font-size="16" font-weight="600" fill="#e2e8f0">{register_records:,}</text>
  
  <!-- Arrows from identification -->
  <line x1="250" y1="155" x2="310" y2="155" stroke="#64748b" stroke-width="1.5" marker-end="url(#arrow)"/>
  <line x1="250" y1="240" x2="310" y2="240" stroke="#64748b" stroke-width="1.5"/>
  <line x1="280" y1="155" x2="280" y2="240" stroke="#64748b" stroke-width="1.5"/>
  
  <!-- SCREENING -->
  <!-- After dedup -->
  <rect x="310" y="120" width="240" height="70" rx="10" fill="url(#boxGrad)" stroke="#8b5cf6" stroke-width="1.5" filter="url(#glow)"/>
  <text x="430" y="142" text-anchor="middle" font-size="12" fill="#94a3b8">去重后记录</text>
  <text x="430" y="167" text-anchor="middle" font-size="20" font-weight="700" fill="#e2e8f0">{after_dedup:,}</text>
  <text x="430" y="183" text-anchor="middle" font-size="10" fill="#64748b">移除 {removed_dup:,} 条重复</text>
  
  <!-- Excluded at screening -->
  <rect x="340" y="220" width="180" height="55" rx="10" fill="url(#exclGrad)" stroke="#ef4444" stroke-width="1.5"/>
  <text x="430" y="242" text-anchor="middle" font-size="12" fill="#fca5a5">标题/摘要排除</text>
  <text x="430" y="264" text-anchor="middle" font-size="18" font-weight="700" fill="#ef4444">{records_excluded_screen:,}</text>
  
  <!-- Arrow down to eligibility -->
  <line x1="430" y1="190" x2="430" y2="300" stroke="#64748b" stroke-width="1.5"/>
  
  <!-- ELIGIBILITY -->
  <!-- Full texts -->
  <rect x="310" y="300" width="240" height="70" rx="10" fill="url(#boxGrad)" stroke="#ec4899" stroke-width="1.5" filter="url(#glow)"/>
  <text x="430" y="322" text-anchor="middle" font-size="12" fill="#94a3b8">全文评估文献</text>
  <text x="430" y="347" text-anchor="middle" font-size="20" font-weight="700" fill="#e2e8f0">{full_texts:,}</text>
  
  <!-- Full text excluded -->
  <rect x="340" y="400" width="180" height="55" rx="10" fill="url(#exclGrad)" stroke="#ef4444" stroke-width="1.5"/>
  <text x="430" y="422" text-anchor="middle" font-size="12" fill="#fca5a5">全文排除</text>
  <text x="430" y="444" text-anchor="middle" font-size="18" font-weight="700" fill="#ef4444">{full_texts_excluded:,}</text>
  
  <!-- Exclusion reasons -->
  <rect x="590" y="290" width="290" height="{max(100, len(exclusion_reasons) * 18 + 40)}" rx="10" fill="rgba(239,68,68,0.05)" stroke="rgba(239,68,68,0.3)" stroke-width="1"/>
  <text x="735" y="312" text-anchor="middle" font-size="12" font-weight="600" fill="#fca5a5">排除原因</text>
{exclusion_text}
  
  <!-- Arrow from full-text to exclusion -->
  <line x1="380" y1="370" x2="380" y2="400" stroke="#ef4444" stroke-width="1.5"/>
  <line x1="550" y1="340" x2="590" y2="340" stroke="#64748b" stroke-width="1" stroke-dasharray="4"/>
  
  <!-- INCLUDED -->
  <line x1="430" y1="370" x2="430" y2="500" stroke="#10b981" stroke-width="2"/>
  
  <rect x="200" y="500" width="200" height="65" rx="10" fill="url(#inclGrad)" stroke="#10b981" stroke-width="2" filter="url(#glow)"/>
  <text x="300" y="522" text-anchor="middle" font-size="12" fill="#6ee7b7">定性分析纳入</text>
  <text x="300" y="550" text-anchor="middle" font-size="24" font-weight="800" fill="#10b981">{qual_included}</text>
  
  <rect x="460" y="500" width="200" height="65" rx="10" fill="url(#inclGrad)" stroke="#10b981" stroke-width="2" filter="url(#glow)"/>
  <text x="560" y="522" text-anchor="middle" font-size="12" fill="#6ee7b7">定量合成纳入 (Meta分析)</text>
  <text x="560" y="550" text-anchor="middle" font-size="24" font-weight="800" fill="#10b981">{quant_included}</text>
  
  <line x1="430" y1="480" x2="300" y2="500" stroke="#10b981" stroke-width="1.5"/>
  <line x1="430" y1="480" x2="560" y2="500" stroke="#10b981" stroke-width="1.5"/>
  
  <!-- Footer -->
  <text x="450" y="600" text-anchor="middle" font-size="10" fill="#475569">MetaForge © 2026 | PRISMA 2020 compliant | 自动生成</text>
</svg>'''
    
    return svg


def generate_prisma_html(data: dict) -> str:
    """生成嵌入网页的PRISMA流程图HTML"""
    svg = generate_prisma_flowchart(data)
    
    return f'''
    <div class="prisma-container" style="background:#0f1629;border-radius:16px;padding:24px;border:1px solid rgba(255,255,255,0.06);">
        <div style="text-align:center;margin-bottom:16px;">
            <span style="display:inline-flex;align-items:center;gap:8px;padding:6px 16px;background:rgba(59,130,246,0.1);border:1px solid rgba(59,130,246,0.3);border-radius:100px;font-size:0.85rem;color:#3b82f6;font-weight:500;">
                📊 PRISMA 2020 Flow Diagram
            </span>
        </div>
        <div style="overflow-x:auto;">
            {svg}
        </div>
        <div style="margin-top:16px;display:flex;gap:12px;justify-content:center;">
            <button onclick="downloadPRISMA()" style="padding:8px 20px;background:rgba(59,130,246,0.1);border:1px solid rgba(59,130,246,0.3);border-radius:8px;color:#60a5fa;font-size:0.85rem;cursor:pointer;">
                ⬇️ 下载 SVG
            </button>
            <button onclick="copyPRISMA()" style="padding:8px 20px;background:rgba(139,92,246,0.1);border:1px solid rgba(139,92,246,0.3);border-radius:8px;color:#a78bfa;font-size:0.85rem;cursor:pointer;">
                📋 复制数据
            </button>
        </div>
    </div>
    <script>
        function downloadPRISMA() {{
            const svg = document.querySelector('.prisma-container svg');
            const blob = new Blob([svg.outerHTML], {{type: 'image/svg+xml'}});
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'prisma_flowchart.svg';
            a.click();
            URL.revokeObjectURL(url);
        }}
        function copyPRISMA() {{
            const data = {json.dumps(data, ensure_ascii=False)};
            navigator.clipboard.writeText(JSON.stringify(data, null, 2));
            alert('PRISMA数据已复制到剪贴板');
        }}
    </script>
    '''
